### ISSUE TITLE
Find arbitrary disappear/appear

### ISSUE THREAD

**Issue by ItsTehStory** [songwongtp/Mask_RCNN_ViewAnalysis#1]
Hey Songwong,
I was wondering if you could give me a quick explanation on how you did the _Find arbitrary_ sections on `detection.py`.
I think I understand the basic idea behind it, but I'd like to know more details on it.
This is my personal account on GitHub. My name is Philippe Ballandras also please contact me at 
philippe.ballandras@wtsparadigm.com or by answering this post.

Thanks,
Philippe

**Comment by songwongtp** [comment]
Hi Philippe,
That part of the code is just a rough fix for random appearance/disappearance of predictions
IoU is used to determine same object in different frames. 
For arbitrary appearance, if a prediction is not matched with any object in its interval of frame, it is then discarded.
For arbitrary disappearance, if a prediction appearing in a current frame disappears in the next frame, but then reappear again in the following frame, the prediction is copied for the next frame.
This code will not work properly if an object/camera moves very fast and there is no overlap of the same objects between consecutive frames.
Hope this help!
Songwong

**Comment by ItsTehStory** [comment]
Hi Songwong,
This does indeed help and explains why I have some problems with weird appearance of detections.
We take 1 frame each 500ms to speed the process for the web, but it acts as if the camera was moving very fast. Do you know how to modify the existing code to prevent this kind of behaviour?
[ I know you too are at an internship so I'll be patient :) ] 
Thank you very much!
Philippe

**Comment by songwongtp** [comment]
Hi Philippe,
You can try adjusting iou_threshold and score_threshold of utils.compute_matches() and the size of interval (i.e. range of for-loops). Still, as I mentioned before, this is just a rough code. It is not expected to return a perfect result. You can also try commenting this part out and see the original prediction of the model. The result might actually look better without this part of the code.
Songwong

**Comment by ItsTehStory** [comment]
Alright! Thanks Songwong I'll try that!
